baseURL: "https://sheharaperera.github.io/" 
title: Shehara Perera
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Research
          url: /research/
          weight: 2
        - name: Design
          url: /design/
          weight: 3        
        - name: Tags
          url: /tags/
          weight: 4
        - name: Archive
          url: /archive/
          weight: 5

params:
    description: "This website hosts Shehara Perera's research, publications, curriculum vitae, and contact information."
    author: Shehara Perera
    googleAnalyticsID: "G-97G4MZ4061"
    images: ["cover.png"]
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","research","design"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shehara Perera
          subtitle: " I am a PhD student in Computational Mechanics at the University of Cambridge. My broad research interests are in computational mechanics and dynamics with applications to aerospace, automotive, and robotics."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: /papers/
            - name: Research
              url: /research/
            - name: Design
              url: /design/
            - name: Tags
              url: /tags/
            - name: Archive
              url: /archive/

    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:ulsp2@cam.ac.uk
        - name: Location
          url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=lrmg3jkAAAAJ&hl=en
        - name: YouTube
          url: https://www.youtube.com/@sheharaperera
        - name: GitHub
          url: https://github.com/sheharaperera
        - name: LinkedIn
          url: https://www.linkedin.com/in/shehara-perera/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Shehara Perera"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

titleCaseStyle: 'none'
