baseURL: "https://sheharaperera.github.io/"
title: Shehara Perera
theme: PaperMod

enableRobotsTXT: true
disableKinds: ["taxonomy", "term", "RSS"]

menu:
    main:
        - name: Home
          url: /
          weight: 1
        - name: Publications
          url: /papers/
          weight: 2
        - name: Teaching & Talks
          url: /teaching/
          weight: 3
        - name: Software
          url: /software/
          weight: 4
        - name: Fun
          url: /fun/
          weight: 5

params:
    description: "Research and publications of Shehara Perera, a PhD student at the University of Cambridge working on quantum algorithms for computational mechanics."
    author: Shehara Perera
    profileMode:
        title: Shehara Perera
        subtitle: " PhD Student at the University of Cambridge, working on developing quantum algorithms for differential equations."
        imageUrl: "/picture.jpeg"
        imageWidth: 160
        imageHeight: 160
        buttons:
            - name: Home
              url: /
            - name: Publications
              url: /papers/
            - name: Teaching & Talks
              url: /teaching/
            - name: Software
              url: /software/
            - name: Fun
              url: /fun/

    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=lrmg3jkAAAAJ&hl=en
        - name: YouTube
          url: https://www.youtube.com/@sheharaperera
        - name: GitHub
          url: https://github.com/sheharaperera
        - name: LinkedIn
          url: https://www.linkedin.com/in/shehara-perera/
        - name: Twitter
          url: https://x.com/SP_Joes/

    label:
        text: "Shehara Perera"
        icon: /favicon.ico
        iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
